### ISSUE TITLE
Resizing image with smaller dimension doesn't work on flutter web, please help !

### ISSUE THREAD

**Issue by gillesgnanagbe** [eyro-labs/image_compression#2]
List<Uint8List> inMemory = [];
    List<PickedFile> _imageFileList = [];
    List<XFile> pickedFileList;
    final ImagePicker _picker = ImagePicker();

    Uint8List a;

    try {
      //Uint8List m = File(path).readAsBytesSync();

      pickedFileList =
          await _picker.pickMultiImage();
      for (int i = 0; i < pickedFileList.length; i++) {
        if (itemsMemory.length + i + 1 <= 9) {
          pickedFileList[i].readAsBytes().then((value) {
            a = value;

            var decodedImage = decodeImageFromList(a).then((value) {
              print(pickedFileList[i].name +
                  " prev width  :" +
                  value.width.toString());
              print(pickedFileList[i].name +
                  " prev height :" +
                  value.height.toString());

              int w = value.width;
              if (value.height > 800) {
                w = ((800 / value.height) * w).toInt();
              }

              final input = ImageFile(
                  rawBytes: a,
                  filePath: pickedFileList[i].name,
                  width: w,
                  height: 800);

              final output = compress(ImageFileConfiguration(input: input));

              setState(() {
                itemsMemory.add(output.rawBytes);
                });

              print('file name' + pickedFileList[i].name);
              print('Input size = ${a.lengthInBytes}');
              print('Output size = ${output.sizeInBytes}');

              var decodedImage1 =
                  decodeImageFromList(output.rawBytes).then((value) {
                print(pickedFileList[i].name +
                    " new width  :" +
                    value.width.toString());
                print(pickedFileList[i].name +
                    " new height :" +
                    value.height.toString());
              });
            });
          });
        }
      }
    } catch (e) {
        print(e.toString());
    } 
  }

**Comment by alann-maulana** [comment]
You can check `image` [library wiki example](https://github.com/brendan-duncan/image/wiki/Examples)

```dart
import 'dart:typed_data';

import 'package:image/image.dart';

void main() {
  final Uint8List rawBytes;
  // Read a jpeg image from rawBytes.
  Image input = decodeJpg(rawBytes);

  // Resize the image to a 120x? thumbnail (maintaining the aspect ratio).
  Image thumbnail = copyResize(input, width: 120);
    
  // Save the thumbnail as a PNG.
  Uint8List output = Uint8List.fromList(encodePng(thumbnail));
}

```
