### ISSUE TITLE
Image size increased instead of reducing[Window].

### ISSUE THREAD

**Issue by CodingWithTashi** [eyro-labs/image_compression#3]
I have used same example app and added image of 2.38 MB size in window and result was weird. Image size got increased to 2.58 MB instead of reduce. Adding gif.    
![image size](https://user-images.githubusercontent.com/25583737/160796867-12c6df72-a078-4ea7-9c4d-7d91c8ad8132.gif)

**Comment by alann-maulana** [comment]
Yeah sometimes this library generate a silly (bigger size) output result comparing the input image.  You can try to configure quality parameter, try set to 40. The output for webp format image, only support for Android and iOS for now. Hope can expand to desktop and web platforms too.

**Comment by CodingWithTashi** [comment]
Yea that would be great, also I noticed there is huge performance difference between desktop, web and mobile devices. If you can improve performace that would very helpfu too.
