### ISSUE TITLE
Compressed image keeps its original dimensions

### ISSUE THREAD

**Issue by warcayac** [eyro-labs/image_compression#5]
## sample code:
```
  void compressWithImageCompression() async {
    final input = ImageFile(
      filePath: imageFile!.path, 
      rawBytes: imageFile!.readAsBytesSync(),
      height: 320,
      width: 240,
    );
    
    await compressInQueue(ImageFileConfiguration(input: input))
    .then((output) {
      info2 = _ImageInfo.fromRaw(output.rawBytes);
      imageCompressed = Image.memory(output.rawBytes, fit: BoxFit.contain);
      setState(() {});
    });
  }
```
## Actual output

![image](https://user-images.githubusercontent.com/7342885/211179616-6241374b-7093-4a58-9da0-4e1a888593c7.png)

Values entered for width and height are not taken into account. Maybe it's the reason why the resulting image is still big compared to other packages/plugins/extensions.

## Output expected

![image](https://user-images.githubusercontent.com/7342885/211179684-4c8736e5-b4fb-43b5-b7b2-57f5ea051142.png)

**Comment by alann-maulana** [comment]
Yeah you can try the Flutter version here [image_compression_flutter](https://github.com/alann-maulana/image_compression_flutter)
