### ISSUE TITLE
old dependencies, please update them

### ISSUE THREAD

**Issue by ZdenekKrcal** [eyro-labs/image_compression#6]
I'm not able to use this package because of old dependencies like image dependency.

**Comment by louisdeveseleer** [comment]
There hasn't any update in a couple years.

It looks like all the "compression" is doing is calling some methods from the image package, so it's easy to do it your way without using this package, with something like that:

```
  final image =decodeImage(rawBytes);
  if (image != null) {
        final output =encodeJpg(image, quality: 80);
  }
```

**Comment by ZdenekKrcal** [comment]
> There hasn't any update in a couple years.
> 
> It looks like all the "compression" is doing is calling some methods from the image package, so it's easy to do it your way without using this package, with something like that:
> 
> ```
>   final image =decodeImage(rawBytes);
>   if (image != null) {
>         final output =encodeJpg(image, quality: 80);
>   }
> ```

Yes I already did it, but thank you.
